### ISSUE TITLE
Explicar melhor o problema e a solução na introdução

### ISSUE THREAD

**Issue by ThiagoLira** [net-map/monografia#20]

**Comment by adrianodennanni** [comment]
Tá absurdamente bem explicado. Gomi, chupa a minha rola seu japa escroto do
caralho

Em 26 de dez de 2016 2:26 PM, "ThiagoLira" <notifications@github.com>
escreveu:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/net-map/monografia/issues/20>, or mute the thread

**Comment by rnagano812** [comment]
O problema ta muito bem explicado mesmo, não tem como colocar mais coisa.
Nos objetivos eu escrevi mais algumas coisas, coloquei sobre a API disponibilizada.
Vejam o que acham
